services:
  database:
    image: postgres:18-alpine
    restart: always
    volumes:
      - db-postgres:/var/lib/postgresql
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  database-batch:
    image: postgres:18-alpine
    restart: always
    volumes:
      - db-postgres-batch:/var/lib/postgresql
    ports:
      - 127.0.0.1:5433:5432
    environment:
      POSTGRES_DB: batch
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  valkey:
    image: valkey/valkey:7-alpine
    command: valkey-server --requirepass ${VALKEY_PASSWORD}
    restart: always
    volumes:
      - db-valkey:/data
    ports:
      - 127.0.0.1:6379:6379

  smtp4dev:
    image: rnwood/smtp4dev
    restart: always
    ports:
      - 127.0.0.1:25:25
      - 127.0.0.1:8025:80

volumes:
  db-postgres:
  db-postgres-batch:
  db-valkey:
