version: "3.9"
services:
  database:
    image: postgres:15-alpine
    restart: always
    volumes:
      - db-postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    labels:
      org.springframework.boot.service-connection: postgres

  valkey:
    image: valkey/valkey:7-alpine
    command: valkey-server --requirepass ${VALKEY_PASSWORD}
    restart: always
    volumes:
      - db-valkey:/data
    ports:
      - 127.0.0.1:6379:6379
    labels:
      org.springframework.boot.service-connection: redis

  smtp4dev:
    image: rnwood/smtp4dev
    restart: always
    ports:
      - 127.0.0.1:25:25
      - 127.0.0.1:8025:80

volumes:
  db-postgres:
  db-valkey: