apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
    - port: 8080
  selector:
    app: {{ .Values.appName }}
    tier: application
  type: ClusterIP