apiVersion: v1
kind: Secret
metadata:
  name: application-secret
  labels:
    app: {{ .Values.appName }}
type: Opaque
immutable: true
data:
  DATABASE_PASSWORD: "{{ .Values.database.password | b64enc }}"
  VALKEY_PASSWORD: "{{ .Values.valkey.password | b64enc }}"
  SMTP_PASSWORD: "{{ .Values.smtp.password | b64enc }}"