apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  labels:
    app: {{ .Values.appName }}
data:
  DATABASE_USERNAME: "{{ .Values.database.username }}"
  {{- if .Values.database.embedded }}
  POSTGRES_URL: "postgresql://database:5432/{{ .Values.database.username }}"
  {{- else }}
  POSTGRES_URL: "postgresql://{{ .Values.database.address }}:{{ .Values.database.port }}/{{ .Values.database.username }}"
  {{- end }}
  POSTGRES_USER: "{{ .Values.database.username }}"
  {{- if .Values.valkey.embedded }}
  VALKEY_HOST: "valkey"
  VALKEY_PORT: "6379"
  {{- else }}
  VALKEY_HOST: "{{ .Values.valkey.address }}"
  VALKEY_PORT: "{{ .Values.valkey.port }}"
  {{- end }}
  SMTP_HOST: "{{ .Values.smtp.address }}"
  SMTP_PORT: "{{ .Values.smtp.port }}"
  SMTP_USERNAME: "{{ .Values.smtp.username }}"
  SMTP_AUTH: "{{ .Values.smtp.auth }}"
  SMTP_STARTTLS: "{{ .Values.smtp.starttls }}"
  MAIL_ACCOUNT_CREATOR: "{{ .Values.mail.accountCreator }}"
  MAIL_DOMAIN_LINKS: "{{ .Values.mail.domainLinks }}"
