apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-batch
  labels:
    app: { { .Values.appName } }
spec:
  selector:
    matchLabels:
      app: { { .Values.appName } }
      tier: database-batch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: { { .Values.appName } }
        tier: database-batch
    spec:
      containers:
        - image: "postgres:18-alpine"
          imagePullPolicy: Always
          name: database-batch

          env:
            - name: POSTGRES_DB
              value: batch
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: application-config
                  key: DATABASE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: DATABASE_PASSWORD

          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "500m"

          ports:
            - containerPort: 5432
              name: database-batch

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database-batch-persistent-storage

      volumes:
        - name: database-batch-persistent-storage
          persistentVolumeClaim:
            claimName: database-batch-pvc
