apiVersion: v1
kind: Secret
metadata:
  name: tenants-config
  labels:
    app: {{ .Values.appName }}
type: Opaque
stringData:
  app.yml: |
    tenantId: "app"
    db:
      jdbcUrl: {{ .Values.tenants.app.db.jdbcUrl | quote }}
      username: {{ .Values.tenants.app.db.username | quote }}
      password: {{ .Values.tenants.app.db.password | quote }}
      schema: {{ .Values.tenants.app.db.schema | quote }}
    redis:
      host: {{ .Values.tenants.app.redis.host | quote }}
      port: {{ .Values.tenants.app.redis.port | default 6379 }}
      {{- if .Values.tenants.app.redis.password }}
      password: {{ .Values.tenants.app.redis.password | quote }}
      {{- end }}
      database: {{ .Values.tenants.app.redis.database | default 0 }}
    smtp:
      host: {{ .Values.tenants.app.smtp.host | quote }}
      port: {{ .Values.tenants.app.smtp.port | default 25 }}
      username: {{ .Values.tenants.app.smtp.username | default "" | quote }}
      password: {{ .Values.tenants.app.smtp.password | default "" | quote }}
      auth: {{ .Values.tenants.app.smtp.auth | default false }}
      starttls: {{ .Values.tenants.app.smtp.starttls | default false }}
      accountCreator: {{ .Values.tenants.app.smtp.accountCreator | quote }}
      domainLinks: {{ .Values.tenants.app.smtp.domainLinks | quote }}
  {{- range .Values.tenants.list }}
  {{ .tenantId }}.yml: |
    tenantId: {{ .tenantId | quote }}
    db:
      jdbcUrl: {{ .db.jdbcUrl | quote }}
      username: {{ .db.username | quote }}
      password: {{ .db.password | quote }}
      schema: {{ .db.schema | quote }}
    redis:
      host: {{ .redis.host | quote }}
      port: {{ .redis.port | default 6379 }}
      {{- if .redis.password }}
      password: {{ .redis.password | quote }}
      {{- end }}
      database: {{ .redis.database | default 0 }}
    smtp:
      host: {{ .smtp.host | quote }}
      port: {{ .smtp.port | default 25 }}
      username: {{ .smtp.username | default "" | quote }}
      password: {{ .smtp.password | default "" | quote }}
      auth: {{ .smtp.auth | default false }}
      starttls: {{ .smtp.starttls | default false }}
      accountCreator: {{ .smtp.accountCreator | quote }}
      domainLinks: {{ .smtp.domainLinks | quote }}
  {{- end }}
