apiVersion: v1
kind: Service
metadata:
  name: valkey
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
    - port: 6379
  selector:
    app: {{ .Values.appName }}
    tier: valkey
  type: ClusterIP