spring.config.import=classpath:domain-dev.properties
spring.docker.compose.enabled=true
spring.docker.compose.file=./docker-compose.yaml
spring.docker.compose.skip.in-tests=false

# Tracing
management.tracing.sampling.probability=1.0

# Documentation
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true