spring.config.import=classpath:domain.properties

# HTTP server
server.port=8080
spring.web.error.whitelabel.enabled=false

# Web MVC
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/

# Application
spring.application.name=demo
spring.threads.virtual.enabled=true
spring.docker.compose.enabled=false
spring.jpa.open-in-view=true
