openapi: 3.1.1
info:
  title: demo
  description: Demo project with authentication
  termsOfService: https://www.flavien.io
  contact:
    email: perier@flavien.io
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8080

tags:
  - name: Application
    description: Application management.
  - name: Session
    description: User session management.
  - name: User
    description: User account management.
  - name: Group
    description: Group and permission management.

paths:
  /api/conf:
    $ref: "paths/application.yaml#/~1api~1conf"
  /api/session/login:
    $ref: "paths/session.yaml#/~1api~1session~1login"
  /api/session/login/web:
    $ref: "paths/session.yaml#/~1api~1session~1login~1web"
  /api/session/logout:
    $ref: "paths/session.yaml#/~1api~1session~1logout"
  /api/session/renew:
    $ref: "paths/session.yaml#/~1api~1session~1renew"
  /api/session/renew/web:
    $ref: "paths/session.yaml#/~1api~1session~1renew~1web"
  /api/sessions:
    $ref: "paths/session.yaml#/~1api~1sessions"
  /api/sessions/{sessionUuid}:
    $ref: "paths/session.yaml#/~1api~1sessions~1%7BsessionUuid%7D"
  /api/users/activate:
    $ref: "paths/user.yaml#/~1api~1users~1activate"
  /api/users/forgot-password:
    $ref: "paths/user.yaml#/~1api~1users~1forgot-password"
  /api/users/password:
    $ref: "paths/user.yaml#/~1api~1users~1password"
  /api/users/me:
    $ref: "paths/user.yaml#/~1api~1users~1me"
  /api/users/me/otp:
    $ref: "paths/user.yaml#/~1api~1users~1me~1otp"
  /api/users/me/otp/confirm:
    $ref: "paths/user.yaml#/~1api~1users~1me~1otp~1confirm"
  /api/users/me/export:
    $ref: "paths/user.yaml#/~1api~1users~1me~1export"
  /api/users/me/permissions:
    $ref: "paths/user.yaml#/~1api~1users~1me~1permissions"
  /api/users/{userMail}:
    $ref: "paths/user.yaml#/~1api~1users~1%7BuserMail%7D"
  /api/users:
    $ref: "paths/user.yaml#/~1api~1users"
  /api/groups:
    $ref: "paths/group.yaml#/~1api~1groups"
  /api/groups/{groupId}:
    $ref: "paths/group.yaml#/~1api~1groups~1%7BgroupId%7D"
  /api/groups/{groupId}/permissions:
    $ref: "paths/group.yaml#/~1api~1groups~1%7BgroupId%7D~1permissions"
  /api/groups/{groupId}/permissions/{permission}:
    $ref: "paths/group.yaml#/~1api~1groups~1%7BgroupId%7D~1permissions~1%7Bpermission%7D"
  /api/users/{userMail}/permissions:
    $ref: "paths/user.yaml#/~1api~1users~1%7BuserMail%7D~1permissions"
  /api/users/{userMail}/permissions/{permission}:
    $ref: "paths/user.yaml#/~1api~1users~1%7BuserMail%7D~1permissions~1%7Bpermission%7D"
  /api/users/{userMail}/groups:
    $ref: "paths/user.yaml#/~1api~1users~1%7BuserMail%7D~1groups"
  /api/users/{userMail}/groups/{groupId}:
    $ref: "paths/user.yaml#/~1api~1users~1%7BuserMail%7D~1groups~1%7BgroupId%7D"
  /api/users/{userMail}/otp:
    $ref: "paths/user.yaml#/~1api~1users~1%7BuserMail%7D~1otp"
  /api/users/{userMail}/reset-password:
    $ref: "paths/user.yaml#/~1api~1users~1%7BuserMail%7D~1reset-password"

components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
