spring.config.import=classpath:domain.properties

spring.application.name=batch
spring.threads.virtual.enabled=true
spring.docker.compose.enabled=false
spring.jpa.open-in-view=false

spring.batch.job.enabled=true
spring.batch.jdbc.initialize-schema=never

app.batch.user-cleanup.warn-threshold-months=11
app.batch.user-cleanup.delete-threshold-months=12
