spring.config.import=classpath:domain.properties

spring.application.name=batch
spring.threads.virtual.enabled=true
spring.docker.compose.enabled=false
spring.jpa.open-in-view=false

spring.batch.job.enabled=false
spring.batch.datasource.url=${BATCH_DB_URL:jdbc:postgresql://127.0.0.1:5432/batch}
spring.batch.datasource.username=${BATCH_DB_USERNAME:admin}
spring.batch.datasource.password=${BATCH_DB_PASSWORD:password}

app.batch.user-cleanup.warn-threshold-months=11
app.batch.user-cleanup.delete-threshold-months=12
