spring.config.import=classpath:domain-dev.properties
spring.docker.compose.enabled=true
spring.docker.compose.file=./docker-compose.yaml
spring.batch.datasource.url=jdbc:postgresql://127.0.0.1:5433/batch
spring.batch.datasource.username=admin
spring.batch.datasource.password=${POSTGRES_PASSWORD:password}
