appName: "app"
registry: "hub.docker.com"

application:
  image: "api"
  imageTag: "latest"

batch:
  image: "batch"
  imageTag: "latest"

database:
  embedded: true
  address: ""
  port: ""
  username: user
  password: password

valkey:
  embedded: true
  address: ""
  port: ""
  password: password

smtp:
  address: localhost
  port: 25
  auth: false
  username: ""
  password: password
  starttls: false

mail:
  accountCreator: "no-reply@flavien.io"
  domainLinks: "https://flavien.io:443"

